"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 100
command_timeout = 1000


[cmd_duration]
min_time = 100
format = '\[â±ï¸[$duration]($style)\]'

[character]
success_symbol = "[ğŸ¦\uf432](010)"
error_symbol = "[ğŸ‘»\uf432](009)"
vicmd_symbol = "[ğŸš€\uf432]](006)"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "ğŸ ~"
format = "[$path]($style)[$read_only]($read_only_style) "

# [directory.substitutions]
# "Documents" = "ğŸ“„ "
# "Downloads" = "ğŸ“¥ "
# "Music" = "ğŸµ "
# "Pictures" = "ğŸ–¼ï¸ "

[package]
disabled = true

[nodejs]
style ="green"
symbol = "\ue718"
format = '\[[$symbol ($version)]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "ğŸŒ±"

[git_commit]
commit_hash_length = 6
tag_symbol = "ğŸ”– "
tag_disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = "\uf308 "

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = "\ufcd1 "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'
