"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 100
command_timeout = 1000

format = """
$directory$all
$character
"""

right_format="$cmd_duration $time"

[time]
disabled = false

[cmd_duration]
min_time = 0
format = '\[â±ï¸[$duration]($style)\]'
style = "238"

[character]
success_symbol = "[ğŸ¦\ufc32](010)"
error_symbol = "[ğŸ‘»\ufc32](009)"
vicmd_symbol = "[ğŸš€\ufc32]](006)"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "ğŸ ~"
format = "[$path]($style)[$read_only]($read_only_style) "

# [directory.substitutions]
# "Documents" = "ğŸ“„ "
# "Downloads" = "ğŸ“¥ "
# "Music" = "ğŸµ "
# "Pictures" = "ğŸ–¼ï¸ "

[package]
format = "[$symbol$version]($style) "
style = "fg:008"
disabled = false
symbol = "ğŸ“¦"

[nodejs]
style ="green"
symbol = "\ue718"
format = "via [$symbol($version)]($style)"

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "ğŸŒ±"

[git_commit]
commit_hash_length = 6
only_detached = true
tag_symbol = "ğŸ”–"
tag_disabled = false
format = "[\\($hash$tag\\)]($style)"
style = "fg:240"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
