"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$rust\
$golang\
$python\
$line_break\
$character
"""

add_newline = true
scan_timeout = 500
command_timeout = 1000
[fill]
symbol = " "
[character]
success_symbol = "[ğŸ¦ ó°œ´](002)"
error_symbol = "[ğŸ‘» ó°œ´](001)"
vimcmd_symbol = "[ğŸ¦„ ó°œ´](002)"

[directory]
truncation_length = 2
truncation_symbol = "~/"
truncate_to_repo = false
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "004"
fish_style_pwd_dir_length=2

[git_branch]
format = "[$branch]($style)"
style = "#6c7086"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = " "
untracked = " "
modified = " "
staged = " "
renamed = " "
deleted = " "
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "008"

[package]
symbol = "ğŸ“¦"
style = "#585b70"
version_format = "${raw}"
format = "[$symbol$version]($style) "
display_private = true


[nodejs]
# symbol="ó°™ "
symbol = "\ue781 "
format = "[$symbol$version]($style)"
style = "green"

[php]
symbol = "ğŸ˜"
disabled = true
format = "[$symbol$version]($style)"

[golang]
symbol = "ğŸ¹ "
style="159"
format = "[$symbol$version]($style)"

[rust]
format = "[$symbol$version]($style)"
style = "red"
symbol = "ğŸ¦€ "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "ó°Œ  "
style = "003"
# [cmd_duration]
# format = "ğŸš€[$duration]($style) "
# style = "005"

# [jobs]
# symbol = "âš™ï¸"
# style = "bold red"
# number_threshold = 1
# format = "[$symbol]($style) "

# [time]
# disabled = true
# format = '[ïº $time]($style)'
# style = "#585b70"
