"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 100
command_timeout = 1000

[character]
success_symbol = "[ğŸ¦ \ufc32](002)"
error_symbol = "[ğŸ‘» \ufc32](001)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
home_symbol = "ğŸ ~"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "004"

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style)"
# symbol = "ï˜ "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '

[package]
format = "[$symbol$version]($style) "
symbol = "ğŸ“¦ "
style = "008"
