"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 100
command_timeout = 1000

format = """
$directory$all
$git_branch$git_status$character
"""


[character]
success_symbol = "[ğŸ¦ \ufc32](002)"
error_symbol = "[ğŸ‘» \ufc32](001)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true
home_symbol = "ğŸ ~"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "004"

[git_branch]
symbol = "\ue708"
format = "[$symbol $branch(:$remote_branch)]($style) "

[package]
symbol = "ğŸ“¦"
format = "[$symbol $version]($style) "

[nodejs]
symbol = "\ue718"
format = "[$symbol $version]($style) "

[php]
symbol = "\ue73d"
format = "[$symbol $version]($style) "
