"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 100
command_timeout = 1000

# format = """
# $directory[$all](008)
# $character
# """


# right_format="[$cmd_duration$time](238)"

[character]
success_symbol = "[ğŸ¦ \ufc32](002)"
error_symbol = "[ğŸ‘» \ufc32](001)"
vicmd_symbol = "[ğŸš€ \ufc32](004)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
home_symbol = "ğŸ  ~"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "004"

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style)"
symbol = "ğŸŒ±"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '

# [git_commit]
# commit_hash_length = 6
# only_detached = false
# tag_symbol = "ğŸ”–"
# tag_disabled = false
# format = "[\\($hash$tag\\)]($style) "
# style = "008"

[package]
format = "[$symbol$version]($style) "
symbol = "ğŸ“¦ "
style = "000"

# [time]
# disabled = false
# format ="[$time]($style)"
# time_format = "%l:%M %p"
# use_12hr = true
# style = "000"

# [cmd_duration]
# min_time = 0
# format = '\[â±ï¸[$duration]($style)\]'
# style = "000"